micronaut:
  application:
    name: allowance
  server:
    port: 8084
    
---
datasources:
  default:
    url: jdbc:mysql:${ALLOWANCE_JDBC_URL}
    username: ${ALLOWANCE_JDBC_USER}
    password: ${ALLOWANCE_JDBC_PASSWORD}
    driverClassName: ${ALLOWANCE_JDBC_DRIVER}
    
---
jpa:
  default:
    packages-to-scan:
      - 'world.deslauriers.domain' 
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect