micronaut:
  application:
    name: allowance
  server:
    port: ${ALLOWANCE_APP_PORT}
    cors:
      enabled:
        true
      configurations:
        web:
          allowedOrigins:
            - ${ALLOWANCE_APP_ALLOWED_ORIGIN}
    
---
datasources:
  default:
    url: jdbc:mysql:${ALLOWANCE_JDBC_URL}
    username: ${ALLOWANCE_JDBC_USER}
    password: ${ALLOWANCE_JDBC_PASSWORD}
    driverClassName: ${ALLOWANCE_JDBC_DRIVER}
    
---
jpa:
  default:
    packages-to-scan:
      - 'world.deslauriers.domain' 
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect

---
allowance:
  indexZero: ${ALLOWANCE_APP_FIRSTNAME_ONE}